# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc429b7ffc5bd63463da93f5cf3a4fb9a3250184ef0de027b460297ae8e78096768e1b53a3017ec8a66e51ea8a4f680de4f37e40f83eba6317178fe18cc7408

test:
  secret_key_base: cad2e0ca3f60d913394d385f453cf3b96c605c760b0876744358f99f04fdcbbff72287ff231b6541ff58fb8e1f6787f457edea9b1bb80e986cc6cb75e89f1533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
